### ISSUE TITLE
i downloaded this and my account got deleted

### ISSUE THREAD

**Issue by mickael-f1** [Soshime/Soshimee-Addons#2]

**Comment by itspbeezy** [comment]
this is a rat

**Comment by mickael-f1** [comment]
> this is a rat

no its not

**Comment by mickael-f1** [comment]
all my coins just magically disappeared i think tbh

**Comment by itspbeezy** [comment]
its a rat

**Comment by itspbeezy** [comment]
> > this is a rat
> 
> no its not

![image](https://github.com/Soshime/Soshimee-Addons/assets/84808671/cf7ca2a9-ceaa-4f1c-b6bd-83ed09b5ceae)
